/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_1.h"
#include "PWM_Out_01_aliases.h"
#include "PWM_Out_01.h"
#include "Clock_1.h"
#include "QuadDec_1.h"
#include "Clock_2.h"
#include "Encoder_A_aliases.h"
#include "Encoder_A.h"
#include "Encoder_B_aliases.h"
#include "Encoder_B.h"
#include "isr_1.h"
#include "ISR_pin_1_aliases.h"
#include "ISR_pin_1.h"
#include "Counter_1.h"
#include "Clock_3.h"
#include "Clock_4.h"
#include "Digital_Output_1_aliases.h"
#include "Digital_Output_1.h"
#include "isr_2.h"
#include "isr_3.h"
#include "ISR_pin_2_aliases.h"
#include "ISR_pin_2.h"
#include "PWM_2.h"
#include "Clock_5.h"
#include "VDAC8_1.h"
#include "Motor_Drive_aliases.h"
#include "Motor_Drive.h"
#include "LCD_Char_1.h"
#include "Potentiometer_In_aliases.h"
#include "Potentiometer_In.h"
#include "ADC_SAR_1.h"
#include "Motor_Current_aliases.h"
#include "Motor_Current.h"
#include "PGA_1.h"
#include "ADC_SAR_2.h"
#include "VDAC8_2.h"
#include "Comp_1.h"
#include "Clock_6.h"
#include "CMP_Out_aliases.h"
#include "CMP_Out.h"
#include "PGA_aliases.h"
#include "PGA.h"
#include "isr_4.h"
#include "DAC_2_aliases.h"
#include "DAC_2.h"
#include "QuadDec_1_Cnt16.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_theACLK.h"
#include "ADC_SAR_2_Bypass_aliases.h"
#include "ADC_SAR_2_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

