/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PGA_1.h"
#include "LCD_Char_1.h"
#include "p3_4_aliases.h"
#include "p3_4.h"
#include "p3_5_aliases.h"
#include "p3_5.h"
#include "p0_3_aliases.h"
#include "p0_3.h"
#include "Opamp_1.h"
#include "ADC_SAR_1.h"
#include "VDAC8_1.h"
#include "p0_2_aliases.h"
#include "p0_2.h"
#include "p0_4_aliases.h"
#include "p0_4.h"
#include "VDAC8_2.h"
#include "p3_0_aliases.h"
#include "p3_0.h"
#include "p3_7_aliases.h"
#include "p3_7.h"
#include "p0_5_aliases.h"
#include "p0_5.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

