/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_1.h"
#include "p3_2_z_axis_aliases.h"
#include "p3_2_z_axis.h"
#include "p3_5_Orange_aliases.h"
#include "p3_5_Orange.h"
#include "p3_4_Yellow_aliases.h"
#include "p3_4_Yellow.h"
#include "LCD_Char_1.h"
#include "p3_6_Pink_aliases.h"
#include "p3_6_Pink.h"
#include "p3_1_aliases.h"
#include "p3_1.h"
#include "p3_0_aliases.h"
#include "p3_0.h"
#include "p3_3_Blue_aliases.h"
#include "p3_3_Blue.h"
#include "ADC_SAR_2.h"
#include "p3_7_Potentiometer_aliases.h"
#include "p3_7_Potentiometer.h"
#include "p0_6_LDR_Top_aliases.h"
#include "p0_6_LDR_Top.h"
#include "p0_7_LDR_Bottom_aliases.h"
#include "p0_7_LDR_Bottom.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_theACLK.h"
#include "ADC_SAR_2_Bypass_aliases.h"
#include "ADC_SAR_2_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

